version: '3.7'

services:
  app:
    build: app/
    restart: always
    entrypoint:
      - /usr/src/app/entrypoint-app.sh
    command: ["python3", "app/main.py"]
    expose:
      - 8080
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - ./app/:/usr/src/app/
    environment:
      SQL_HOST: db
      SQL_PORT: 5432
    networks:
      - net_inner

  db:
    image: postgres:11.5
    restart: always
    env_file:
      - db.env
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data/
    networks:
      - net_inner

networks:
  net_inner:
    driver: bridge
